name: hub-obs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install gcloud SDK
      run: |
        curl -L https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-173.0.0-linux-x86_64.tar.gz | tar --directory ${HOME} --extract --gzip --file -
    - name: Install Kubectl
      run: |
        mkdir -p ${HOME}/bin
        curl -L https://storage.googleapis.com/kubernetes-release/release/v1.18.2/bin/linux/amd64/kubectl > ${HOME}/bin/kubectl
        chmod +x ${HOME}/bin/kubectl
    - name: Install helm
      run: |
        curl -L https://storage.googleapis.com/kubernetes-helm/helm-v2.16.7-linux-amd64.tar.gz | tar --directory ${HOME} --extract --gzip --file -
  mv ${HOME}/linux-amd64/helm ${HOME}/bin/helm
