name: hub

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.1.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Install gcloud SDK
      run: curl -L https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-173.0.0-linux-x86_64.tar.gz | tar --directory ${HOME} --extract --gzip --file -
    - name: Install Kubectl
      run: |
        mkdir -p ${HOME}/bin
        curl -L https://storage.googleapis.com/kubernetes-release/release/v1.18.2/bin/linux/amd64/kubectl > ${HOME}/bin/kubectl
        chmod +x ${HOME}/bin/kubectl
    - name: Install helm
      run: |
        curl -L https://storage.googleapis.com/kubernetes-helm/helm-v2.16.7-linux-amd64.tar.gz | tar --directory ${HOME} --extract --gzip --file -
        mv ${HOME}/linux-amd64/helm ${HOME}/bin/helm
    - name: Set up helm
      run: |
        helm init --client-only
        helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
        helm repo update
